//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ServidorPassword {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Acceso", Namespace="http://schemas.datacontract.org/2004/07/AccesoADatos")]
    [System.SerializableAttribute()]
    public partial class Acceso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Jugador[] JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAccesoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Jugador[] Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseniaField, value) != true)) {
                    this.contraseniaField = value;
                    this.RaisePropertyChanged("contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAcceso {
            get {
                return this.idAccesoField;
            }
            set {
                if ((this.idAccesoField.Equals(value) != true)) {
                    this.idAccesoField = value;
                    this.RaisePropertyChanged("idAcceso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/AccesoADatos")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Acceso AccesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Amistad[] AmistadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.DetalleLogro[] DetalleLogroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.DetallePartida[] DetallePartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Estadistica EstadisticaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FKIdPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FKidAccesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FKidEstadisticaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Perfil PerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estadoJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Acceso Acceso {
            get {
                return this.AccesoField;
            }
            set {
                if ((object.ReferenceEquals(this.AccesoField, value) != true)) {
                    this.AccesoField = value;
                    this.RaisePropertyChanged("Acceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Amistad[] Amistad {
            get {
                return this.AmistadField;
            }
            set {
                if ((object.ReferenceEquals(this.AmistadField, value) != true)) {
                    this.AmistadField = value;
                    this.RaisePropertyChanged("Amistad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.DetalleLogro[] DetalleLogro {
            get {
                return this.DetalleLogroField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleLogroField, value) != true)) {
                    this.DetalleLogroField = value;
                    this.RaisePropertyChanged("DetalleLogro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.DetallePartida[] DetallePartida {
            get {
                return this.DetallePartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallePartidaField, value) != true)) {
                    this.DetallePartidaField = value;
                    this.RaisePropertyChanged("DetallePartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Estadistica Estadistica {
            get {
                return this.EstadisticaField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadisticaField, value) != true)) {
                    this.EstadisticaField = value;
                    this.RaisePropertyChanged("Estadistica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FKIdPerfil {
            get {
                return this.FKIdPerfilField;
            }
            set {
                if ((this.FKIdPerfilField.Equals(value) != true)) {
                    this.FKIdPerfilField = value;
                    this.RaisePropertyChanged("FKIdPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FKidAcceso {
            get {
                return this.FKidAccesoField;
            }
            set {
                if ((this.FKidAccesoField.Equals(value) != true)) {
                    this.FKidAccesoField = value;
                    this.RaisePropertyChanged("FKidAcceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FKidEstadistica {
            get {
                return this.FKidEstadisticaField;
            }
            set {
                if ((this.FKidEstadisticaField.Equals(value) != true)) {
                    this.FKidEstadisticaField = value;
                    this.RaisePropertyChanged("FKidEstadistica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Perfil Perfil {
            get {
                return this.PerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilField, value) != true)) {
                    this.PerfilField = value;
                    this.RaisePropertyChanged("Perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidosField, value) != true)) {
                    this.apellidosField = value;
                    this.RaisePropertyChanged("apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estadoJugador {
            get {
                return this.estadoJugadorField;
            }
            set {
                if ((this.estadoJugadorField.Equals(value) != true)) {
                    this.estadoJugadorField = value;
                    this.RaisePropertyChanged("estadoJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugador {
            get {
                return this.idJugadorField;
            }
            set {
                if ((this.idJugadorField.Equals(value) != true)) {
                    this.idJugadorField = value;
                    this.RaisePropertyChanged("idJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estadistica", Namespace="http://schemas.datacontract.org/2004/07/AccesoADatos")]
    [System.SerializableAttribute()]
    public partial class Estadistica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Jugador[] JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEstadisticaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int partidasGanadasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int partidasPerdidasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string puntajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Jugador[] Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEstadistica {
            get {
                return this.idEstadisticaField;
            }
            set {
                if ((this.idEstadisticaField.Equals(value) != true)) {
                    this.idEstadisticaField = value;
                    this.RaisePropertyChanged("idEstadistica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int partidasGanadas {
            get {
                return this.partidasGanadasField;
            }
            set {
                if ((this.partidasGanadasField.Equals(value) != true)) {
                    this.partidasGanadasField = value;
                    this.RaisePropertyChanged("partidasGanadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int partidasPerdidas {
            get {
                return this.partidasPerdidasField;
            }
            set {
                if ((this.partidasPerdidasField.Equals(value) != true)) {
                    this.partidasPerdidasField = value;
                    this.RaisePropertyChanged("partidasPerdidas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string puntaje {
            get {
                return this.puntajeField;
            }
            set {
                if ((object.ReferenceEquals(this.puntajeField, value) != true)) {
                    this.puntajeField = value;
                    this.RaisePropertyChanged("puntaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Perfil", Namespace="http://schemas.datacontract.org/2004/07/AccesoADatos")]
    [System.SerializableAttribute()]
    public partial class Perfil : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Jugador[] JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rutaImagenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Jugador[] Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPerfil {
            get {
                return this.idPerfilField;
            }
            set {
                if ((this.idPerfilField.Equals(value) != true)) {
                    this.idPerfilField = value;
                    this.RaisePropertyChanged("idPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreUsuarioField, value) != true)) {
                    this.nombreUsuarioField = value;
                    this.RaisePropertyChanged("nombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rutaImagen {
            get {
                return this.rutaImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.rutaImagenField, value) != true)) {
                    this.rutaImagenField = value;
                    this.RaisePropertyChanged("rutaImagen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amistad", Namespace="http://schemas.datacontract.org/2004/07/AccesoADatos")]
    [System.SerializableAttribute()]
    public partial class Amistad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FKidJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Jugador JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fechaRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAmistadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorAmigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FKidJugador {
            get {
                return this.FKidJugadorField;
            }
            set {
                if ((this.FKidJugadorField.Equals(value) != true)) {
                    this.FKidJugadorField = value;
                    this.RaisePropertyChanged("FKidJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Jugador Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaRespuesta {
            get {
                return this.fechaRespuestaField;
            }
            set {
                if ((this.fechaRespuestaField.Equals(value) != true)) {
                    this.fechaRespuestaField = value;
                    this.RaisePropertyChanged("fechaRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaSolicitud {
            get {
                return this.fechaSolicitudField;
            }
            set {
                if ((this.fechaSolicitudField.Equals(value) != true)) {
                    this.fechaSolicitudField = value;
                    this.RaisePropertyChanged("fechaSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAmistad {
            get {
                return this.idAmistadField;
            }
            set {
                if ((this.idAmistadField.Equals(value) != true)) {
                    this.idAmistadField = value;
                    this.RaisePropertyChanged("idAmistad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugadorAmigo {
            get {
                return this.idJugadorAmigoField;
            }
            set {
                if ((this.idJugadorAmigoField.Equals(value) != true)) {
                    this.idJugadorAmigoField = value;
                    this.RaisePropertyChanged("idJugadorAmigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleLogro", Namespace="http://schemas.datacontract.org/2004/07/AccesoADatos")]
    [System.SerializableAttribute()]
    public partial class DetalleLogro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FKIdJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FKIdLogroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Jugador JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Logro LogroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDetalleLogroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FKIdJugador {
            get {
                return this.FKIdJugadorField;
            }
            set {
                if ((this.FKIdJugadorField.Equals(value) != true)) {
                    this.FKIdJugadorField = value;
                    this.RaisePropertyChanged("FKIdJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FKIdLogro {
            get {
                return this.FKIdLogroField;
            }
            set {
                if ((this.FKIdLogroField.Equals(value) != true)) {
                    this.FKIdLogroField = value;
                    this.RaisePropertyChanged("FKIdLogro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Jugador Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Logro Logro {
            get {
                return this.LogroField;
            }
            set {
                if ((object.ReferenceEquals(this.LogroField, value) != true)) {
                    this.LogroField = value;
                    this.RaisePropertyChanged("Logro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDetalleLogro {
            get {
                return this.idDetalleLogroField;
            }
            set {
                if ((this.idDetalleLogroField.Equals(value) != true)) {
                    this.idDetalleLogroField = value;
                    this.RaisePropertyChanged("idDetalleLogro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetallePartida", Namespace="http://schemas.datacontract.org/2004/07/AccesoADatos")]
    [System.SerializableAttribute()]
    public partial class DetallePartida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FKidJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FKidPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Jugador JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Partida PartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDetallePartidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FKidJugador {
            get {
                return this.FKidJugadorField;
            }
            set {
                if ((this.FKidJugadorField.Equals(value) != true)) {
                    this.FKidJugadorField = value;
                    this.RaisePropertyChanged("FKidJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FKidPartida {
            get {
                return this.FKidPartidaField;
            }
            set {
                if ((this.FKidPartidaField.Equals(value) != true)) {
                    this.FKidPartidaField = value;
                    this.RaisePropertyChanged("FKidPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Jugador Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Partida Partida {
            get {
                return this.PartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.PartidaField, value) != true)) {
                    this.PartidaField = value;
                    this.RaisePropertyChanged("Partida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDetallePartida {
            get {
                return this.idDetallePartidaField;
            }
            set {
                if ((this.idDetallePartidaField.Equals(value) != true)) {
                    this.idDetallePartidaField = value;
                    this.RaisePropertyChanged("idDetallePartida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Logro", Namespace="http://schemas.datacontract.org/2004/07/AccesoADatos")]
    [System.SerializableAttribute()]
    public partial class Logro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.DetalleLogro[] DetalleLogroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idLogroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reglasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.DetalleLogro[] DetalleLogro {
            get {
                return this.DetalleLogroField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleLogroField, value) != true)) {
                    this.DetalleLogroField = value;
                    this.RaisePropertyChanged("DetalleLogro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idLogro {
            get {
                return this.idLogroField;
            }
            set {
                if ((this.idLogroField.Equals(value) != true)) {
                    this.idLogroField = value;
                    this.RaisePropertyChanged("idLogro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reglas {
            get {
                return this.reglasField;
            }
            set {
                if ((object.ReferenceEquals(this.reglasField, value) != true)) {
                    this.reglasField = value;
                    this.RaisePropertyChanged("reglas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Partida", Namespace="http://schemas.datacontract.org/2004/07/AccesoADatos")]
    [System.SerializableAttribute()]
    public partial class Partida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.DetallePartida[] DetallePartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Pregunta[] PreguntaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAnfitrionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modoJuegoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.DetallePartida[] DetallePartida {
            get {
                return this.DetallePartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallePartidaField, value) != true)) {
                    this.DetallePartidaField = value;
                    this.RaisePropertyChanged("DetallePartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Pregunta[] Pregunta {
            get {
                return this.PreguntaField;
            }
            set {
                if ((object.ReferenceEquals(this.PreguntaField, value) != true)) {
                    this.PreguntaField = value;
                    this.RaisePropertyChanged("Pregunta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoPartida {
            get {
                return this.codigoPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoPartidaField, value) != true)) {
                    this.codigoPartidaField = value;
                    this.RaisePropertyChanged("codigoPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadoPartida {
            get {
                return this.estadoPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoPartidaField, value) != true)) {
                    this.estadoPartidaField = value;
                    this.RaisePropertyChanged("estadoPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAnfitrion {
            get {
                return this.idAnfitrionField;
            }
            set {
                if ((this.idAnfitrionField.Equals(value) != true)) {
                    this.idAnfitrionField = value;
                    this.RaisePropertyChanged("idAnfitrion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPartida {
            get {
                return this.idPartidaField;
            }
            set {
                if ((this.idPartidaField.Equals(value) != true)) {
                    this.idPartidaField = value;
                    this.RaisePropertyChanged("idPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modoJuego {
            get {
                return this.modoJuegoField;
            }
            set {
                if ((object.ReferenceEquals(this.modoJuegoField, value) != true)) {
                    this.modoJuegoField = value;
                    this.RaisePropertyChanged("modoJuego");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pregunta", Namespace="http://schemas.datacontract.org/2004/07/AccesoADatos")]
    [System.SerializableAttribute()]
    public partial class Pregunta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FKidPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Partida PartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Respuesta[] RespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int duracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPreguntaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pregunta1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string respuestaCorrectaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FKidPartida {
            get {
                return this.FKidPartidaField;
            }
            set {
                if ((this.FKidPartidaField.Equals(value) != true)) {
                    this.FKidPartidaField = value;
                    this.RaisePropertyChanged("FKidPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Partida Partida {
            get {
                return this.PartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.PartidaField, value) != true)) {
                    this.PartidaField = value;
                    this.RaisePropertyChanged("Partida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Respuesta[] Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int duracion {
            get {
                return this.duracionField;
            }
            set {
                if ((this.duracionField.Equals(value) != true)) {
                    this.duracionField = value;
                    this.RaisePropertyChanged("duracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPregunta {
            get {
                return this.idPreguntaField;
            }
            set {
                if ((this.idPreguntaField.Equals(value) != true)) {
                    this.idPreguntaField = value;
                    this.RaisePropertyChanged("idPregunta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pregunta1 {
            get {
                return this.pregunta1Field;
            }
            set {
                if ((object.ReferenceEquals(this.pregunta1Field, value) != true)) {
                    this.pregunta1Field = value;
                    this.RaisePropertyChanged("pregunta1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string respuestaCorrecta {
            get {
                return this.respuestaCorrectaField;
            }
            set {
                if ((object.ReferenceEquals(this.respuestaCorrectaField, value) != true)) {
                    this.respuestaCorrectaField = value;
                    this.RaisePropertyChanged("respuestaCorrecta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/AccesoADatos")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FKidPreguntaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServidorPassword.Pregunta PreguntaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string respuesta1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FKidPregunta {
            get {
                return this.FKidPreguntaField;
            }
            set {
                if ((this.FKidPreguntaField.Equals(value) != true)) {
                    this.FKidPreguntaField = value;
                    this.RaisePropertyChanged("FKidPregunta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServidorPassword.Pregunta Pregunta {
            get {
                return this.PreguntaField;
            }
            set {
                if ((object.ReferenceEquals(this.PreguntaField, value) != true)) {
                    this.PreguntaField = value;
                    this.RaisePropertyChanged("Pregunta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRespuesta {
            get {
                return this.idRespuestaField;
            }
            set {
                if ((this.idRespuestaField.Equals(value) != true)) {
                    this.idRespuestaField = value;
                    this.RaisePropertyChanged("idRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string respuesta1 {
            get {
                return this.respuesta1Field;
            }
            set {
                if ((object.ReferenceEquals(this.respuesta1Field, value) != true)) {
                    this.respuesta1Field = value;
                    this.RaisePropertyChanged("respuesta1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://schemas.datacontract.org/2004/07/AccesoADatos.Auxiliares")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAccesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaImagenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAcceso {
            get {
                return this.IdAccesoField;
            }
            set {
                if ((this.IdAccesoField.Equals(value) != true)) {
                    this.IdAccesoField = value;
                    this.RaisePropertyChanged("IdAcceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJugador {
            get {
                return this.IdJugadorField;
            }
            set {
                if ((this.IdJugadorField.Equals(value) != true)) {
                    this.IdJugadorField = value;
                    this.RaisePropertyChanged("IdJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPerfil {
            get {
                return this.IdPerfilField;
            }
            set {
                if ((this.IdPerfilField.Equals(value) != true)) {
                    this.IdPerfilField = value;
                    this.RaisePropertyChanged("IdPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaImagen {
            get {
                return this.RutaImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaImagenField, value) != true)) {
                    this.RutaImagenField = value;
                    this.RaisePropertyChanged("RutaImagen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorPassword.IServicioChat", CallbackContract=typeof(Cliente.ServidorPassword.IServicioChatCallback))]
    public interface IServicioChat {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioChat/Chatear")]
        void Chatear(string chat);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioChat/Chatear")]
        System.Threading.Tasks.Task ChatearAsync(string chat);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChatCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChat/Responder", ReplyAction="http://tempuri.org/IServicioChat/ResponderResponse")]
        void Responder(string respuesta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChatChannel : Cliente.ServidorPassword.IServicioChat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioChatClient : System.ServiceModel.DuplexClientBase<Cliente.ServidorPassword.IServicioChat>, Cliente.ServidorPassword.IServicioChat {
        
        public ServicioChatClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServicioChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServicioChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioChatClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Chatear(string chat) {
            base.Channel.Chatear(chat);
        }
        
        public System.Threading.Tasks.Task ChatearAsync(string chat) {
            return base.Channel.ChatearAsync(chat);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorPassword.IServicioGestionAcceso")]
    public interface IServicioGestionAcceso {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestionAcceso/RegistrarNuevoJugador", ReplyAction="http://tempuri.org/IServicioGestionAcceso/RegistrarNuevoJugadorResponse")]
        int RegistrarNuevoJugador(Cliente.ServidorPassword.Acceso acceso, Cliente.ServidorPassword.Perfil perfil, Cliente.ServidorPassword.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestionAcceso/RegistrarNuevoJugador", ReplyAction="http://tempuri.org/IServicioGestionAcceso/RegistrarNuevoJugadorResponse")]
        System.Threading.Tasks.Task<int> RegistrarNuevoJugadorAsync(Cliente.ServidorPassword.Acceso acceso, Cliente.ServidorPassword.Perfil perfil, Cliente.ServidorPassword.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestionAcceso/ValidarInicioDeSesion", ReplyAction="http://tempuri.org/IServicioGestionAcceso/ValidarInicioDeSesionResponse")]
        int ValidarInicioDeSesion(Cliente.ServidorPassword.Acceso acceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestionAcceso/ValidarInicioDeSesion", ReplyAction="http://tempuri.org/IServicioGestionAcceso/ValidarInicioDeSesionResponse")]
        System.Threading.Tasks.Task<int> ValidarInicioDeSesionAsync(Cliente.ServidorPassword.Acceso acceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestionAcceso/ValidarNuevoRegistro", ReplyAction="http://tempuri.org/IServicioGestionAcceso/ValidarNuevoRegistroResponse")]
        bool ValidarNuevoRegistro(Cliente.ServidorPassword.Acceso acceso, Cliente.ServidorPassword.Perfil perfil, Cliente.ServidorPassword.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestionAcceso/ValidarNuevoRegistro", ReplyAction="http://tempuri.org/IServicioGestionAcceso/ValidarNuevoRegistroResponse")]
        System.Threading.Tasks.Task<bool> ValidarNuevoRegistroAsync(Cliente.ServidorPassword.Acceso acceso, Cliente.ServidorPassword.Perfil perfil, Cliente.ServidorPassword.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestionAcceso/EncriptarContrasenia", ReplyAction="http://tempuri.org/IServicioGestionAcceso/EncriptarContraseniaResponse")]
        string EncriptarContrasenia(string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestionAcceso/EncriptarContrasenia", ReplyAction="http://tempuri.org/IServicioGestionAcceso/EncriptarContraseniaResponse")]
        System.Threading.Tasks.Task<string> EncriptarContraseniaAsync(string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestionAcceso/ValidarNombreUsuario", ReplyAction="http://tempuri.org/IServicioGestionAcceso/ValidarNombreUsuarioResponse")]
        bool ValidarNombreUsuario(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestionAcceso/ValidarNombreUsuario", ReplyAction="http://tempuri.org/IServicioGestionAcceso/ValidarNombreUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ValidarNombreUsuarioAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestionAcceso/RecuperarCuentaPorCorreo", ReplyAction="http://tempuri.org/IServicioGestionAcceso/RecuperarCuentaPorCorreoResponse")]
        Cliente.ServidorPassword.Cuenta RecuperarCuentaPorCorreo(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestionAcceso/RecuperarCuentaPorCorreo", ReplyAction="http://tempuri.org/IServicioGestionAcceso/RecuperarCuentaPorCorreoResponse")]
        System.Threading.Tasks.Task<Cliente.ServidorPassword.Cuenta> RecuperarCuentaPorCorreoAsync(string correo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioGestionAccesoChannel : Cliente.ServidorPassword.IServicioGestionAcceso, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioGestionAccesoClient : System.ServiceModel.ClientBase<Cliente.ServidorPassword.IServicioGestionAcceso>, Cliente.ServidorPassword.IServicioGestionAcceso {
        
        public ServicioGestionAccesoClient() {
        }
        
        public ServicioGestionAccesoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioGestionAccesoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGestionAccesoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGestionAccesoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegistrarNuevoJugador(Cliente.ServidorPassword.Acceso acceso, Cliente.ServidorPassword.Perfil perfil, Cliente.ServidorPassword.Jugador jugador) {
            return base.Channel.RegistrarNuevoJugador(acceso, perfil, jugador);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarNuevoJugadorAsync(Cliente.ServidorPassword.Acceso acceso, Cliente.ServidorPassword.Perfil perfil, Cliente.ServidorPassword.Jugador jugador) {
            return base.Channel.RegistrarNuevoJugadorAsync(acceso, perfil, jugador);
        }
        
        public int ValidarInicioDeSesion(Cliente.ServidorPassword.Acceso acceso) {
            return base.Channel.ValidarInicioDeSesion(acceso);
        }
        
        public System.Threading.Tasks.Task<int> ValidarInicioDeSesionAsync(Cliente.ServidorPassword.Acceso acceso) {
            return base.Channel.ValidarInicioDeSesionAsync(acceso);
        }
        
        public bool ValidarNuevoRegistro(Cliente.ServidorPassword.Acceso acceso, Cliente.ServidorPassword.Perfil perfil, Cliente.ServidorPassword.Jugador jugador) {
            return base.Channel.ValidarNuevoRegistro(acceso, perfil, jugador);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarNuevoRegistroAsync(Cliente.ServidorPassword.Acceso acceso, Cliente.ServidorPassword.Perfil perfil, Cliente.ServidorPassword.Jugador jugador) {
            return base.Channel.ValidarNuevoRegistroAsync(acceso, perfil, jugador);
        }
        
        public string EncriptarContrasenia(string contrasenia) {
            return base.Channel.EncriptarContrasenia(contrasenia);
        }
        
        public System.Threading.Tasks.Task<string> EncriptarContraseniaAsync(string contrasenia) {
            return base.Channel.EncriptarContraseniaAsync(contrasenia);
        }
        
        public bool ValidarNombreUsuario(string nombreUsuario) {
            return base.Channel.ValidarNombreUsuario(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarNombreUsuarioAsync(string nombreUsuario) {
            return base.Channel.ValidarNombreUsuarioAsync(nombreUsuario);
        }
        
        public Cliente.ServidorPassword.Cuenta RecuperarCuentaPorCorreo(string correo) {
            return base.Channel.RecuperarCuentaPorCorreo(correo);
        }
        
        public System.Threading.Tasks.Task<Cliente.ServidorPassword.Cuenta> RecuperarCuentaPorCorreoAsync(string correo) {
            return base.Channel.RecuperarCuentaPorCorreoAsync(correo);
        }
    }
}
