//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cliente.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Btn_AceptarGlobal {
            get {
                return ResourceManager.GetString("Btn_AceptarGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string Btn_CambiarContrasenia {
            get {
                return ResourceManager.GetString("Btn_CambiarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Btn_CancelarGlobal {
            get {
                return ResourceManager.GetString("Btn_CancelarGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string Btn_Enviar {
            get {
                return ResourceManager.GetString("Btn_Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string Btn_GuardarCambios {
            get {
                return ResourceManager.GetString("Btn_GuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string Btn_IniciarSesión {
            get {
                return ResourceManager.GetString("Btn_IniciarSesión", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado.
        /// </summary>
        public static string Btn_Invitado {
            get {
                return ResourceManager.GetString("Btn_Invitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvide Mi Contraseña.
        /// </summary>
        public static string Btn_OlvideMiContrasena {
            get {
                return ResourceManager.GetString("Btn_OlvideMiContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarme.
        /// </summary>
        public static string Btn_Registrarme {
            get {
                return ResourceManager.GetString("Btn_Registrarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido(s).
        /// </summary>
        public static string Lbl_Apellidos {
            get {
                return ResourceManager.GetString("Lbl_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Lbl_ContraseñaGlobal {
            get {
                return ResourceManager.GetString("Lbl_ContraseñaGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string Lbl_CorreoGlobal {
            get {
                return ResourceManager.GetString("Lbl_CorreoGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Lbl_DescripcionPerfil {
            get {
                return ResourceManager.GetString("Lbl_DescripcionPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña ha sido cambiada correctamente.
        /// </summary>
        public static string Lbl_MensajeContraseñaPerfil {
            get {
                return ResourceManager.GetString("Lbl_MensajeContraseñaPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre(s).
        /// </summary>
        public static string Lbl_Nombre {
            get {
                return ResourceManager.GetString("Lbl_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string Lbl_NombreUsuarioPerfil {
            get {
                return ResourceManager.GetString("Lbl_NombreUsuarioPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string Lbl_NombreUsuarioRegistro {
            get {
                return ResourceManager.GetString("Lbl_NombreUsuarioRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizar perfil.
        /// </summary>
        public static string Lbl_PersonalizarPerfil {
            get {
                return ResourceManager.GetString("Lbl_PersonalizarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener al menos 8 caracteres, una letra mayúscula, un número y un carácter especial..
        /// </summary>
        public static string Lbl_PoliticaContraseña {
            get {
                return ResourceManager.GetString("Lbl_PoliticaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Lbl_TituloJuegoGlobal {
            get {
                return ResourceManager.GetString("Lbl_TituloJuegoGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los cambios han sido guardados. .
        /// </summary>
        public static string MensajeCambiosGuardados {
            get {
                return ResourceManager.GetString("MensajeCambiosGuardados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise que la información de los campos sea correcta..
        /// </summary>
        public static string MensajeCamposIncorrectos {
            get {
                return ResourceManager.GetString("MensajeCamposIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise que todos los campos solicitados estén llenos. .
        /// </summary>
        public static string MensajeCamposRequeridos {
            get {
                return ResourceManager.GetString("MensajeCamposRequeridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo elegido ya se encuentra registrado, intente iniciar sesión. .
        /// </summary>
        public static string MensajeCorreoRegistrado {
            get {
                return ResourceManager.GetString("MensajeCorreoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se le enviará una nueva contraseña al correo que registre..
        /// </summary>
        public static string MensajeEnvioContrasena {
            get {
                return ResourceManager.GetString("MensajeEnvioContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay conexión con la base de datos. Por favor, inténtelo más tarde. .
        /// </summary>
        public static string MensajeErrorBaseDeDatos {
            get {
                return ResourceManager.GetString("MensajeErrorBaseDeDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay conexión a la red. Por favor, inténtelo más tarde. .
        /// </summary>
        public static string MensajeErrorConexion {
            get {
                return ResourceManager.GetString("MensajeErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise que la información de los campos sea correcta. .
        /// </summary>
        public static string MensajeInformacionInvalida {
            get {
                return ResourceManager.GetString("MensajeInformacionInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su registro ha sido exitoso, ahora puede iniciar sesión con su correo y contraseña elegida..
        /// </summary>
        public static string MensajeRegistroExitoso {
            get {
                return ResourceManager.GetString("MensajeRegistroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario elegido no está disponible, elija otro. .
        /// </summary>
        public static string MensajeUsuarioNoDisponible {
            get {
                return ResourceManager.GetString("MensajeUsuarioNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string Title_Inicio {
            get {
                return ResourceManager.GetString("Title_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio Sesion.
        /// </summary>
        public static string Title_InicioSesion {
            get {
                return ResourceManager.GetString("Title_InicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizar perfil.
        /// </summary>
        public static string Title_PersonalizarPerfil {
            get {
                return ResourceManager.GetString("Title_PersonalizarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string Title_Registro {
            get {
                return ResourceManager.GetString("Title_Registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        public static string VentanaEmergenteAdvertencia {
            get {
                return ResourceManager.GetString("VentanaEmergenteAdvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación de acción.
        /// </summary>
        public static string VentanaEmergenteConfirmacion {
            get {
                return ResourceManager.GetString("VentanaEmergenteConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error.
        /// </summary>
        public static string VentanaEmergenteError {
            get {
                return ResourceManager.GetString("VentanaEmergenteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito.
        /// </summary>
        public static string VentanaEmergenteExito {
            get {
                return ResourceManager.GetString("VentanaEmergenteExito", resourceCulture);
            }
        }
    }
}
