//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cliente.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string AsuntoNuevaContrasenia {
            get {
                return ResourceManager.GetString("AsuntoNuevaContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Btn_AceptarGlobal {
            get {
                return ResourceManager.GetString("Btn_AceptarGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AgregarAmigo.
        /// </summary>
        public static string Btn_AgregarAmigo {
            get {
                return ResourceManager.GetString("Btn_AgregarAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string Btn_CambiarContrasenia {
            get {
                return ResourceManager.GetString("Btn_CambiarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Btn_CancelarGlobal {
            get {
                return ResourceManager.GetString("Btn_CancelarGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elegir imagen de jugador.
        /// </summary>
        public static string Btn_ElegirImagen {
            get {
                return ResourceManager.GetString("Btn_ElegirImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string Btn_Enviar {
            get {
                return ResourceManager.GetString("Btn_Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar a español.
        /// </summary>
        public static string Btn_Español {
            get {
                return ResourceManager.GetString("Btn_Español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string Btn_GuardarCambios {
            get {
                return ResourceManager.GetString("Btn_GuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar a inglés.
        /// </summary>
        public static string Btn_Inglés {
            get {
                return ResourceManager.GetString("Btn_Inglés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string Btn_IniciarSesión {
            get {
                return ResourceManager.GetString("Btn_IniciarSesión", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado.
        /// </summary>
        public static string Btn_Invitado {
            get {
                return ResourceManager.GetString("Btn_Invitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar.
        /// </summary>
        public static string Btn_Invitar {
            get {
                return ResourceManager.GetString("Btn_Invitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar.
        /// </summary>
        public static string Btn_Jugar {
            get {
                return ResourceManager.GetString("Btn_Jugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de 
        ///Amigos.
        /// </summary>
        public static string Btn_ListaDeAmigos {
            get {
                return ResourceManager.GetString("Btn_ListaDeAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logros.
        /// </summary>
        public static string Btn_Logros {
            get {
                return ResourceManager.GetString("Btn_Logros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvide Mi Contraseña.
        /// </summary>
        public static string Btn_OlvideMiContrasena {
            get {
                return ResourceManager.GetString("Btn_OlvideMiContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string Btn_Rechazar {
            get {
                return ResourceManager.GetString("Btn_Rechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarme.
        /// </summary>
        public static string Btn_Registrarme {
            get {
                return ResourceManager.GetString("Btn_Registrarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string Btn_RegresarGlobal {
            get {
                return ResourceManager.GetString("Btn_RegresarGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string Btn_SalirGlobal {
            get {
                return ResourceManager.GetString("Btn_SalirGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes.
        /// </summary>
        public static string Btn_Solicitudes {
            get {
                return ResourceManager.GetString("Btn_Solicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse.
        /// </summary>
        public static string Btn_Unirse {
            get {
                return ResourceManager.GetString("Btn_Unirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver perfil.
        /// </summary>
        public static string Btn_VerPerfil {
            get {
                return ResourceManager.GetString("Btn_VerPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has sido invitado a una nueva partida.
        /// </summary>
        public static string CorreoInvitacionPartida {
            get {
                return ResourceManager.GetString("CorreoInvitacionPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        public static string CuerpoContrasenia {
            get {
                return ResourceManager.GetString("CuerpoContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string Estado_Conectado {
            get {
                return ResourceManager.GetString("Estado_Conectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string Estado_Conexion {
            get {
                return ResourceManager.GetString("Estado_Conexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string Estado_Desconectado {
            get {
                return ResourceManager.GetString("Estado_Desconectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Amigo.
        /// </summary>
        public static string Lbl_AgregarAmigo {
            get {
                return ResourceManager.GetString("Lbl_AgregarAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string Lbl_Amigos {
            get {
                return ResourceManager.GetString("Lbl_Amigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido(s).
        /// </summary>
        public static string Lbl_Apellidos {
            get {
                return ResourceManager.GetString("Lbl_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por correo.
        /// </summary>
        public static string Lbl_BuscarPorCorreo {
            get {
                return ResourceManager.GetString("Lbl_BuscarPorCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de idioma.
        /// </summary>
        public static string Lbl_CambioIdioma {
            get {
                return ResourceManager.GetString("Lbl_CambioIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo de sala.
        /// </summary>
        public static string Lbl_CodigoDeSala {
            get {
                return ResourceManager.GetString("Lbl_CodigoDeSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        public static string Lbl_ContraseñaActual {
            get {
                return ResourceManager.GetString("Lbl_ContraseñaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Lbl_ContraseñaGlobal {
            get {
                return ResourceManager.GetString("Lbl_ContraseñaGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string Lbl_CorreoGlobal {
            get {
                return ResourceManager.GetString("Lbl_CorreoGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Lbl_DescripcionPerfil {
            get {
                return ResourceManager.GetString("Lbl_DescripcionPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadisticas.
        /// </summary>
        public static string Lbl_Estadisticas {
            get {
                return ResourceManager.GetString("Lbl_Estadisticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conectado.
        /// </summary>
        public static string Lbl_EstadoConectado {
            get {
                return ResourceManager.GetString("Lbl_EstadoConectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha conectado.
        /// </summary>
        public static string Lbl_EstadoConexion {
            get {
                return ResourceManager.GetString("Lbl_EstadoConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconectado.
        /// </summary>
        public static string Lbl_EstadoDesconectado {
            get {
                return ResourceManager.GetString("Lbl_EstadoDesconectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganador.
        /// </summary>
        public static string Lbl_Ganador {
            get {
                return ResourceManager.GetString("Lbl_Ganador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string Lbl_Inicio {
            get {
                return ResourceManager.GetString("Lbl_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio Sesion.
        /// </summary>
        public static string Lbl_InicioSesion {
            get {
                return ResourceManager.GetString("Lbl_InicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores.
        /// </summary>
        public static string Lbl_Jugadores {
            get {
                return ResourceManager.GetString("Lbl_Jugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gana una partida.
        /// </summary>
        public static string Lbl_Logro1 {
            get {
                return ResourceManager.GetString("Lbl_Logro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gana 10 partidas.
        /// </summary>
        public static string Lbl_Logro2 {
            get {
                return ResourceManager.GetString("Lbl_Logro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtén 200 de puntaje en una partida.
        /// </summary>
        public static string Lbl_Logro3 {
            get {
                return ResourceManager.GetString("Lbl_Logro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gana una partida en la dificultad más alta.
        /// </summary>
        public static string Lbl_Logro4 {
            get {
                return ResourceManager.GetString("Lbl_Logro4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtén 600 de puntaje en una partida.
        /// </summary>
        public static string Lbl_Logro5 {
            get {
                return ResourceManager.GetString("Lbl_Logro5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logros.
        /// </summary>
        public static string Lbl_Logros {
            get {
                return ResourceManager.GetString("Lbl_Logros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre(s).
        /// </summary>
        public static string Lbl_Nombre {
            get {
                return ResourceManager.GetString("Lbl_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de 
        ///usuario.
        /// </summary>
        public static string Lbl_NombreUsuarioPerfil {
            get {
                return ResourceManager.GetString("Lbl_NombreUsuarioPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string Lbl_NombreUsuarioRegistro {
            get {
                return ResourceManager.GetString("Lbl_NombreUsuarioRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string Lbl_NuevaContrasenia {
            get {
                return ResourceManager.GetString("Lbl_NuevaContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida Finalizada.
        /// </summary>
        public static string Lbl_PartidaFinalizada {
            get {
                return ResourceManager.GetString("Lbl_PartidaFinalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas Ganadas.
        /// </summary>
        public static string Lbl_PartidasGanadas {
            get {
                return ResourceManager.GetString("Lbl_PartidasGanadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas Jugadas.
        /// </summary>
        public static string Lbl_PartidasJugadas {
            get {
                return ResourceManager.GetString("Lbl_PartidasJugadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas Perdidas.
        /// </summary>
        public static string Lbl_PartidasPerdidas {
            get {
                return ResourceManager.GetString("Lbl_PartidasPerdidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizar perfil.
        /// </summary>
        public static string Lbl_PersonalizarPerfil {
            get {
                return ResourceManager.GetString("Lbl_PersonalizarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario podrá contener solo números y letras.
        /// </summary>
        public static string Lbl_PoliticaNombreUsuario {
            get {
                return ResourceManager.GetString("Lbl_PoliticaNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntaje.
        /// </summary>
        public static string Lbl_Puntaje {
            get {
                return ResourceManager.GetString("Lbl_Puntaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string Lbl_Registro {
            get {
                return ResourceManager.GetString("Lbl_Registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Imagen de Jugador.
        /// </summary>
        public static string Lbl_SeleccionarImagen {
            get {
                return ResourceManager.GetString("Lbl_SeleccionarImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soliciudes de amistad.
        /// </summary>
        public static string Lbl_SolicitudesDeAmistad {
            get {
                return ResourceManager.GetString("Lbl_SolicitudesDeAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Lbl_TituloJuegoGlobal {
            get {
                return ResourceManager.GetString("Lbl_TituloJuegoGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya ha enviado o le han enviado una solicitud de amistad el jugador.
        /// </summary>
        public static string MensajeAmistadAnterior {
            get {
                return ResourceManager.GetString("MensajeAmistadAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los cambios han sido guardados. .
        /// </summary>
        public static string MensajeCambiosGuardados {
            get {
                return ResourceManager.GetString("MensajeCambiosGuardados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise que la información de los campos sea correcta..
        /// </summary>
        public static string MensajeCamposIncorrectos {
            get {
                return ResourceManager.GetString("MensajeCamposIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise que todos los campos solicitados estén llenos. .
        /// </summary>
        public static string MensajeCamposRequeridos {
            get {
                return ResourceManager.GetString("MensajeCamposRequeridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se han encontrado los catálogos necesarios para completar esta operación, inténtelo más tarde..
        /// </summary>
        public static string MensajeCatalogosFaltantes {
            get {
                return ResourceManager.GetString("MensajeCatalogosFaltantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código proporcionado no pertenece a ninguna partida, asegurese de colocar el código correcto.
        /// </summary>
        public static string MensajeCodigoPartidaInexistente {
            get {
                return ResourceManager.GetString("MensajeCodigoPartidaInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña ha sido cambiada correctamente.
        /// </summary>
        public static string MensajeContraseñaPerfil {
            get {
                return ResourceManager.GetString("MensajeContraseñaPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo ha sido enviado.
        /// </summary>
        public static string MensajeCorreoEnviado {
            get {
                return ResourceManager.GetString("MensajeCorreoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo elegido ya se encuentra registrado, intente iniciar sesión. .
        /// </summary>
        public static string MensajeCorreoRegistrado {
            get {
                return ResourceManager.GetString("MensajeCorreoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta con la que intentas acceder esta en uso..
        /// </summary>
        public static string MensajeCuentaEnUso {
            get {
                return ResourceManager.GetString("MensajeCuentaEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se le enviará una nueva contraseña al correo que registre..
        /// </summary>
        public static string MensajeEnvioContrasena {
            get {
                return ResourceManager.GetString("MensajeEnvioContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay conexión con la base de datos. Por favor, inténtelo más tarde. .
        /// </summary>
        public static string MensajeErrorBaseDeDatos {
            get {
                return ResourceManager.GetString("MensajeErrorBaseDeDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error de comunicación con el servidor. Verifique la conexión con el servidor..
        /// </summary>
        public static string MensajeErrorComunicacion {
            get {
                return ResourceManager.GetString("MensajeErrorComunicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La conexión al servidor no se pudo hacer. Verifique la conexión al servidor y vuelva intentarlo..
        /// </summary>
        public static string MensajeErrorConexion {
            get {
                return ResourceManager.GetString("MensajeErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo no pudo ser enviado, intentálo más tarde.
        /// </summary>
        public static string MensajeErrorEnvioCorreo {
            get {
                return ResourceManager.GetString("MensajeErrorEnvioCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tiempo de espera ha terminado. Verifique la conexión con el servidor..
        /// </summary>
        public static string MensajeErrorTiempoTerminado {
            get {
                return ResourceManager.GetString("MensajeErrorTiempoTerminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desesas expulsar al jugador de la partida?.
        /// </summary>
        public static string MensajeExpulsionJugador {
            get {
                return ResourceManager.GetString("MensajeExpulsionJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise que la información de los campos sea correcta. .
        /// </summary>
        public static string MensajeInformacionInvalida {
            get {
                return ResourceManager.GetString("MensajeInformacionInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes iniciar la partida, ya que no eres su anfitrión.
        /// </summary>
        public static string MensajeNoEresAnfitrion {
            get {
                return ResourceManager.GetString("MensajeNoEresAnfitrion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida ha llegado al límite de jugadores, juega otra partida..
        /// </summary>
        public static string MensajePartidaConLimiteJugadores {
            get {
                return ResourceManager.GetString("MensajePartidaConLimiteJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida ya no se encuentra disponible.
        /// </summary>
        public static string MensajePartidaNoDisponible {
            get {
                return ResourceManager.GetString("MensajePartidaNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su registro ha sido exitoso, ahora puede iniciar sesión con su correo y contraseña elegida..
        /// </summary>
        public static string MensajeRegistroExitoso {
            get {
                return ResourceManager.GetString("MensajeRegistroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualmente no tienes solicitudes de amistad.
        /// </summary>
        public static string MensajeSinSolicitudes {
            get {
                return ResourceManager.GetString("MensajeSinSolicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario o correo elegido no está disponible, elija otro. .
        /// </summary>
        public static string MensajeUsuarioNoDisponible {
            get {
                return ResourceManager.GetString("MensajeUsuarioNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de sala.
        /// </summary>
        public static string Txbl_CodigoDeSala {
            get {
                return ResourceManager.GetString("Txbl_CodigoDeSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificil.
        /// </summary>
        public static string Txbl_Dificil {
            get {
                return ResourceManager.GetString("Txbl_Dificil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificultad.
        /// </summary>
        public static string Txbl_Dificultad {
            get {
                return ResourceManager.GetString("Txbl_Dificultad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doctorado.
        /// </summary>
        public static string Txbl_Doctorado {
            get {
                return ResourceManager.GetString("Txbl_Doctorado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fácil.
        /// </summary>
        public static string Txbl_Facil {
            get {
                return ResourceManager.GetString("Txbl_Facil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licenciatura.
        /// </summary>
        public static string Txbl_Licenciatura {
            get {
                return ResourceManager.GetString("Txbl_Licenciatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maestria.
        /// </summary>
        public static string Txbl_Maestria {
            get {
                return ResourceManager.GetString("Txbl_Maestria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medio.
        /// </summary>
        public static string Txbl_Medio {
            get {
                return ResourceManager.GetString("Txbl_Medio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener al menos 8 caracteres, una letra mayúscula, un número y un carácter especial..
        /// </summary>
        public static string Txbl_PoliticaContraseña {
            get {
                return ResourceManager.GetString("Txbl_PoliticaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        public static string VentanaEmergenteAdvertencia {
            get {
                return ResourceManager.GetString("VentanaEmergenteAdvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El idioma cambiará a inglés
        ///Los cambios se aplicarán al reiniciar el juago.
        /// </summary>
        public static string VentanaEmergenteCambioIdioma {
            get {
                return ResourceManager.GetString("VentanaEmergenteCambioIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación de acción.
        /// </summary>
        public static string VentanaEmergenteConfirmacion {
            get {
                return ResourceManager.GetString("VentanaEmergenteConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error.
        /// </summary>
        public static string VentanaEmergenteError {
            get {
                return ResourceManager.GetString("VentanaEmergenteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito.
        /// </summary>
        public static string VentanaEmergenteExito {
            get {
                return ResourceManager.GetString("VentanaEmergenteExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se expulsó al jugador correctamente.
        /// </summary>
        public static string VentanaEmergenteExpulsado {
            get {
                return ResourceManager.GetString("VentanaEmergenteExpulsado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se expulsará al juador de la partida.
        /// </summary>
        public static string VentanaEmergenteExpulsion {
            get {
                return ResourceManager.GetString("VentanaEmergenteExpulsion", resourceCulture);
            }
        }
    }
}
